language: generic
sudo: false
dist: trusty

env:
  global:
    BYOND_MAJOR="511"
    BYOND_MINOR="1385"

# ALL MAPS MUST BE PRESENT HERE
# IF THEY ARE NOT, YOUR BUILD WILL FAIL
  matrix:
    - TEST=CODE

cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

before_script:
  - jdk_switcher use openjdk8

before_install:
  - unset _JAVA_OPTIONS
  - chmod +x test/run-test.sh
addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
      - python
      - python-pip

script:
  - test/run-test.sh